build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: true

naming:
  FunctionNaming:
    ignoreAnnotated: ["Composable"]

style:
  UnusedPrivateMember:
    allowedNames: "(_|ignored|expected|serialVersionUID|.*Preview.*)"
